### ISSUE TITLE
Add some descriptive text on setting breaks / color maps for rasters

### ISSUE THREAD

**Issue by lwasser** [NEONInc/NEON-Data-Skills#15]
We added a section on applying color maps with specific break points when rendering rasters in R. we should add some background on what a break is and how a color map works. There's got to be something out there on this!

http://neondataskills.org/Data-Workshops/NEON-lidar-Rasters-R/

**Comment by chrlaney** [comment]
It's also not clear what you're trying to show with this section:
brk <- c(250, 300, 350, 400,450,500)
image(DEM, zlim=c(250,300), col=col, breaks=brk)

I think the range of 250-500 in brk is overriding zlim = c(250,300).
What do you want the users to get out of this part?

Also, I think you might be able to use the image.plot() function in the fields package to generate labels for each break. Haven't had a chance to try it - I need to work through the remaining parts of the tutorial!

**Comment by lwasser** [comment]
OOoh – you’re right. I added that quickly.

There are two things to learn in that section.


1.       If you want you can limit how much of the data are plotted. This is good if you have crazy outlier data or you just have some other goals.

2.       You can also (or instead) establish breaks where you can plot data within specific range values.

I believe that Natalie is working on some background information about breaks SO – let’s let her do her thing first. Then, I think we should remove the zlims and explain what this is all doing.

I think I just saw a PR from Natalie too! ☺

**Comment by lwasser** [comment]
I think the breaks should be more clear. do we need to clarify producing color ramps or vector lists of colors to apply to plots?

**Comment by neondataskills** [comment]
This is now addressed in the intro to raster series (http://neondataskills.org/tutorial-series/raster-data-series/). It is unclear which lesson was originally referred to as the link is broken and none of the LiDAR tutorials have a similar URL.
