### ISSUE TITLE
HDFView lesson issues with hypersctral image

### ISSUE THREAD

**Issue by fluby** [NEONInc/NEON-Data-Skills#30]
I am not getting the hyperspectral image to display properly in HDFView. I am just seeing a black screen.
I am wondering if it is related to this:
on http://neondataskills.org/HDF5/Exploring-Data-HDFView/, it states:
Under height, make sure dim 1 is selected.
Under width, make sure dim 3 is selected. 

However, there are only dim 0-dim2 available in my drop down menus in either HDF View 2.10 or 2.11. Thoughts?

**Comment by lwasser** [comment]
oops! that's a mistake. the HDF file uses 0-based indexing so it should be dimensions 1 and 2 which would be 2 and 3 in a 1-based indexing world. that's a mistake!  Adding the URL so i can fix it :) great catch and thank you! https://github.com/lwasser/NEON-Data-Skills/blob/gh-pages/_posts/HDF5/2014-11-05-Exploring-HDF5-in-HDFView-HDF5.md

**Comment by fluby** [comment]
Thanks, Leah - now it's working!  Also, I think adding an image to the lesson page of what the hyperspectral image should look like in HDFView would be handy.

**Comment by neondataskills** [comment]
This was fixed at sometime in the past.
