### ISSUE TITLE
Fix formatting on DPLYR Lessons and clean up title

### ISSUE THREAD

**Issue by lwasser** [NEONInc/NEON-Data-Skills#37]
feedback from Sarah E

On the website there is some weird formatting stuff going on, with ?? showing up where it shouldn’t, example if you’??re dealing with large data it’??s 
http://neondataskills.org/R/GREPL-Filter-Piping-in-DPLYR-Using-R/

-change title of the dplyr lesson to since it's largely not about grepl?  Maybe just leaving it as filter-piping-in-DPLYR-Using-R.

**Comment by mjones01** [comment]
The formatting issue has been fixed.  I'm leaving the title as is since the page has been live for >18 months and GREPL is in the lesson.
