### ISSUE TITLE
hyperspectral lesson - some math weirdness in the example

### ISSUE THREAD

**Issue by scelmendorf** [NEONInc/NEON-Data-Skills#38]
Full Width Half Max (FWHM)

The full width half max (FWHM) will also often be reported in a multi or hyperspectral dataset. This value represents the spread of the band around that center point.

The Full Width Half Max (FWHM) of a band relates to the distance in nanometers between the band center and the edge of the band. In this case, the FWHM for Band C is 2.5 nm.

**Comment by scelmendorf** [comment]
Sorry, it submitted before I finished writing.  Anyhow, your example shows a band that is blown up (to the right), that goes from 790 to 790 (though not in the blown-up version), and then says the fhwm is 2.5.  I think a labeling error, but it's confusing.

**Comment by lwasser** [comment]
hey - is this the page that you're looking at?
http://neondataskills.org/HDF5/About-Hyperspectral-Remote-Sensing-Data/#full-width-half-max-fwhm

**Comment by scelmendorf** [comment]
Yes, that is the page

**Comment by mjones01** [comment]
[This](http://neondataskills.org/HDF5/About-Hyperspectral-Remote-Sensing-Data/#full-width-half-max-fwhm) appears to have been fixed at some point.  Closing this Issue.
