### ISSUE TITLE
Cheatsheets 

### ISSUE THREAD

**Issue by mjones01** [NEONInc/NEON-Data-Skills#50]
There is a duplicated cheatsheet page.

**Comment by lwasser** [comment]
refer to : https://github.com/lwasser/NEON-Data-Skills/pull/49/commits

**Comment by lwasser** [comment]
I propose we disable cheatsheets for the time being. they are too hard to curate and the page isn't rendering properly. @mjones01 sound ok?

**Comment by mjones01** [comment]
Sounds good.  For now let's keep a list of them (gDoc in ? folder), so the information isn't lost.

**Comment by chayadecacao** [comment]
yup! i am not going to delete them. i'm just going to disable all public
links to them!

leah
