### ISSUE TITLE
NEONInc link at top of NEONDataSkills page broken

### ISSUE THREAD

**Issue by mjones01** [NEONInc/NEON-Data-Skills#52]
On main NEONdataskills.org page, the link back to NEONinc.org is broken.  Current link is neoninc.org and code needs to change to www.neoninc.org.   
I'm happy to change but I can't find the file that contains this code.

**Comment by lwasser** [comment]
Weird. It works for me.
I will have a look.
Leah

Please excuse any typos - sent from my Android.

-----Original Message-----

**Comment by mjones01** [comment]
Interesting.  It works from my phone (Android) but not PC or Mac laptops.

**Comment by coolinwilliams** [comment]
Works for me from chrome and Firefox.

Colin

**Comment by lwasser** [comment]
I just made a change to the config file. Sometimes the .neoninc.org redirects and sometimes it doesnt.

See if it works after refreshing. It works on my phone. I'm at the vet w my pup now :)
Leah

Please excuse any typos - sent from my Android.

-----Original Message-----

**Comment by mjones01** [comment]
Works on my Mac laptop and phone now!  Thanks.

**Comment by mjones01** [comment]
Closing issue as it now appears to work from PC & Mac in Chrome and Firefox and Mobile Android platforms.
