### ISSUE TITLE
Set working Dir Lesson is Live - Please review

### ISSUE THREAD

**Issue by lwasser** [NEONInc/NEON-Data-Skills#61]
Ok - this is (*i think*) the most current version. Please review. if it looks OK, close the issue!
We are done with the lesson for now :) @mjones01 

http://neondataskills.org/R/Set-Working-Directory

**Comment by mjones01** [comment]
Looks good. And the links from the other lessons work (well the 3 I tried).  Closing.

**Comment by mjones01** [comment]
Actually, I can't close this one.

**Comment by lwasser** [comment]
Ok I'll check out your permissions for the repo! Closing this in the meantime
