### ISSUE TITLE
Knitr Script: Fix extension in filename quirk

### ISSUE THREAD

**Issue by mjones01** [NEONInc/NEON-Data-Skills#65]
The knitr scripts throughout the repo(s) need to have the `rmd.files <-` object code changed (~line 96).  
Change to: 

`rmd.files <- list.files(file.path(gitRepoPath, postsDir), pattern="\\.Rmd$", full.names = TRUE )`

it is currently `pattern=*.Rmd`.  

The problem is that any time a file with Rmd in the file name (not extension; e.g. 2016-06-10-Rmd03-RMarkdown.md) is in a folder that is being knit it will also be re-knit.

**Comment by neondataskills** [comment]
Done with new RMD2R file
