### ISSUE TITLE
Institute Page needs updating 

### ISSUE THREAD

**Issue by mjones01** [NEONInc/NEON-Data-Skills#66]
http://neondataskills.org/workshop-event/NEON-Work-With-Data-Insitute-2016

* name change -> to NEON Data Institute
*  Incorrect formatting on last line of list
* Broken link for more information @ bottom of page: link to neonscience -> http://www.neonscience.org/learn-experience/work-data-institute 
* Do we want to add link for the Data Institute webpage?

**Comment by neondataskills** [comment]
Fixed in PR https://github.com/NEONInc/NEON-Data-Skills/pull/68
